#!/bin/bash

CFILES="bar_list.c board.c game.c helpers.c io.c main.c player.c rules.c"

NUMARGS=1
EXIT_FAILURE=1

if [[ "$#" -ne "$NUMARGS" ]] ; then
    echo "Error: There should be two arguments: the name of the executable," \
        "and the testing file." >&2
    exit
fi
exe=./backgammon
input=$1
output=$(basename $input)_results
seed=$(echo $(basename $input) | cut -d_ -f2)

gcc -ansi -Wall -pedantic ${CFILES} -o $exe -g

valgrind --track-origins=yes --quiet $exe $seed < $input > $output 
diff ${input}_output $output 

